image: node:9.10.0 # 若版號差距大時，可以試試拉高版本看看gitlab支援了沒

pages:
  script:
  - npm install
  - ./node_modules/hexo/bin/hexo clean
  - ./node_modules/hexo/bin/hexo deploy
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
    key: project
  only:
  - master